// Generated by CoffeeScript 1.6.3
(function() {
  var Character, LocalStrategy, MongoURI, SteamStrategy, app, express, fs, http, io, moment, mongoose, passport, path, pathTasks, routes, server, user, _ref;

  express = require('express');

  routes = require('./../routes');

  user = require('./../routes/user');

  http = require('http');

  path = require('path');

  passport = require('passport');

  fs = require('fs');

  LocalStrategy = require("passport-local").Strategy;

  SteamStrategy = require('passport-steam').Strategy;

  mongoose = require('mongoose');

  app = express();

  pathTasks = require('./pathtasks');

  moment = require('moment');

  io = require('socket.io');

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(require('stylus').middleware(__dirname + '/../public'));

  app.use(express.methodOverride());

  app.configure(function() {
    app.use(express["static"](path.join(__dirname, '/../public')));
    app.use(express.cookieParser('catboard key'));
    app.use(express.bodyParser());
    app.use(express.session());
    app.use(passport.initialize());
    app.use(passport.session());
    return app.use(app.router);
  });

  server = http.createServer(app);

  io = io.listen(server);

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

  MongoURI = (_ref = process.env.MONGOLAB_URI) != null ? _ref : 'mongodb://localhost/roguelife';

  mongoose.connect(MongoURI);

  /* PASSPORT*/


  app.isAuthenticated = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    }
    return res.redirect('/login');
  };

  passport.serializeUser(function(user, done) {
    return done(null, user.id);
  });

  passport.deserializeUser(function(id, done) {
    return Character.findById(id, function(err, user) {
      return done(err, user);
    });
  });

  passport.use(new LocalStrategy(function(username, password, done) {
    return Character.findOne({
      username: username
    }, function(err, user) {
      if (err) {
        return done(err);
      }
      if (!user) {
        return done(null, false, {
          message: 'Incorrect username'
        });
      }
      if (password !== user.password) {
        return done(null, false, {
          message: 'Incorrect password'
        });
      }
      return done(null, user);
    });
  }));

  passport.use(new SteamStrategy({
    returnURL: 'http://roguelife.herokuapp.com/auth/steam/return',
    realm: 'http://roguelife.herokuapp.com/'
  }, function(identifier, done) {
    User.findByOpenID({
      openId: identifier
    }, function(err, user) {
      return done(err, user);
    });
  }));

  Character = mongoose.model('Character', {
    username: {
      type: String,
      required: true,
      unique: true
    },
    email: {
      type: String,
      required: true,
      unique: true
    },
    password: {
      type: String,
      required: true
    },
    openID: {
      type: String
    },
    health: {
      type: Number,
      "default": 100
    },
    currentHealth: {
      type: Number,
      "default": 100
    },
    mana: {
      type: Number,
      "default": 50
    },
    currentMana: {
      type: Number,
      "default": 50
    },
    experience: {
      type: Number,
      "default": 0
    },
    level: {
      type: Number,
      "default": 1
    },
    currentQuests: {
      type: Array,
      "default": []
    },
    completedQuests: {
      type: Array,
      "default": []
    },
    dailies: {
      type: Array,
      "default": []
    },
    path: {
      type: String
    },
    avatar: {
      type: String
    }
  });

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  app.get('/', function(req, res) {
    return res.render('index', {
      userCharacter: req.user
    });
  });

  app.get('/login', function(req, res) {
    return res.render('login');
  });

  app.post('/signin', passport.authenticate('local'), function(req, res) {
    console.log(req.user.username);
    return res.send({
      redirect: '/users/' + req.user._id,
      charData: req.user
    });
  });

  app.get('/charData', app.isAuthenticated, function(req, res) {
    return res.send(req.user);
  });

  app.get('/users/:id', app.isAuthenticated, function(req, res) {
    console.log('USER IN DASH', req.user);
    return Character.find({
      username: req.user.username
    }, function(err, data) {
      if (err) {
        return console.log('error', err);
      } else {
        console.log('char', data);
        return res.render('dash', {
          userCharacter: data[0],
          dailies: pathTasks.dailies
        });
      }
    });
  });

  app.get('/login', function(req, res) {
    return res.render('login');
  });

  app.post('/signup', function(req, res) {
    return Character.findOne({
      username: req.body.username
    }, function(err, user) {
      var newUser;
      if (user) {
        return res.send('Already a user!');
      } else {
        newUser = new Character({
          email: req.body.email,
          password: req.body.password,
          username: req.body.username
        });
        newUser.save();
        console.log('UserID', newUser._id);
        return passport.authenticate('local', function(req, res) {
          return res.redirect('/');
        });
      }
    });
  });

  app.post('/chosenpath', function(req, res) {
    console.log('user', req.user);
    console.log('BODY PATH', req.body.path);
    Character.update({
      username: req.user.username
    }, {
      $set: {
        path: req.body.path
      }
    }, function(err, char) {
      char = char[0];
      console.log('CHAR!!!', char);
      if (err) {
        return console.log('error choosepath', err);
      }
    });
    return res.send('success!');
  });

  app.post('/removeQuest', function(req, res) {
    Character.update({
      username: req.user.username
    }, {
      $pull: {
        currentQuests: {
          questName: req.body.questName
        }
      }
    }, function(err, char) {
      if (err) {
        return console.log('err remove', err);
      }
    });
    return res.send('removed');
  });

  app.post('/updateQuest', function(req, res) {
    Character.update({
      username: req.user.username
    }, {
      $push: {
        currentQuests: {
          questName: req.body.questName,
          startQuest: moment().format('lll')
        }
      }
    }, function(err, char) {});
    return res.send('updated');
  });

  app.post('/removeDaily', function(req, res) {
    Character.update({
      username: req.user.username
    }, {
      $pull: {
        dailies: req.body.dailyName
      }
    }, function(err, char) {
      if (err) {
        return console.log('err remove', err);
      }
    });
    return res.send('removed');
  });

  app.post('/updateDaily', function(req, res) {
    Character.update({
      username: req.user.username
    }, {
      $push: {
        dailies: req.body.dailyName
      }
    }, function(err, char) {});
    return res.send('updated');
  });

  app.get('/auth/steam/', passport.authenticate('steam', function(req, res) {
    return res.send('steamsuccess');
  }));

  app.get('/auth/steam/callback', passport.authenticate('steam', function(req, res) {
    console.log('auth steam cb', req.user);
    res.redirect('/');
  }));

  app.get('/auth/steam/return', passport.authenticate('steam', function(req, res) {
    console.log('steam req.user', req.user);
    res.send(req.query);
  }));

  app.get('/logout', function(req, res) {
    req.logOut();
    return res.redirect('/');
  });

  /* SOCKETS*/


  user = {};

  io.sockets.on('connection', function(socket) {
    user[socket.id] = socket.id;
    io.sockets.emit('connected', {
      id: socket.id
    });
    return socket.on('updateDaily', function(dailyName) {});
  });

}).call(this);
