// Generated by CoffeeScript 1.6.3
(function() {
  var Character, LocalStrategy, MongoURI, OpenIDStrategy, SteamStrategy, app, express, fs, http, mongoose, passport, path, pathTasks, routes, server, user, _ref;

  express = require('express');

  routes = require('./../routes');

  user = require('./../routes/user');

  http = require('http');

  path = require('path');

  passport = require('passport');

  fs = require('fs');

  LocalStrategy = require("passport-local").Strategy;

  OpenIDStrategy = require('passport-openid').Strategy;

  SteamStrategy = require('passport-steam').Strategy;

  mongoose = require('mongoose');

  app = express();

  pathTasks = require('./pathtasks');

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(require('stylus').middleware(__dirname + '/../public'));

  app.use(express.methodOverride());

  app.configure(function() {
    app.use(express["static"](path.join(__dirname, '/../public')));
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express.session({
      secret: 'catboard key'
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    return app.use(app.router);
  });

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

  MongoURI = (_ref = process.env.MONGOLAB_URI) != null ? _ref : 'mongodb://localhost/roguelife';

  mongoose.connect(MongoURI);

  /* PASSPORT*/


  app.isAuthenticated = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    } else {
      return res.redirect('/login');
    }
  };

  passport.serializeUser(function(user, done) {
    return done(null, user.id);
  });

  passport.deserializeUser(function(id, done) {
    return Character.findById(id, function(err, user) {
      return done(err, user);
    });
  });

  passport.use(new LocalStrategy(function(username, password, done) {
    return Character.findOne({
      username: username
    }, function(err, user) {
      if (err) {
        return done(err);
      }
      if (!user) {
        return done(null, false, {
          message: 'Incorrect username'
        });
      }
      if (password !== user.password) {
        return done(null, false, {
          message: 'Incorrect password'
        });
      }
      return done(null, user);
    });
  }));

  passport.use(new SteamStrategy({
    returnURL: 'http://' + process.env.domain + '/auth/steam/return',
    realm: 'http://' + process.env.domain + '/'
  }, function(identifier, done) {
    User.findByOpenID({
      openId: identifier
    }, function(err, user) {});
    if (err) {
      return done(err);
    }
    if (!user) {
      return done(null, false, {
        message: 'Incorrect username'
      });
    }
    if (password !== user.password) {
      return done(null, false, {
        message: 'Incorrect password'
      });
    }
    return done(null, user);
  }));

  Character = mongoose.model('Character', {
    username: {
      type: String,
      required: true,
      unique: true
    },
    email: {
      type: String,
      required: true,
      unique: true
    },
    password: {
      type: String,
      required: true
    },
    health: {
      type: Number,
      "default": 100
    },
    currentHealth: {
      type: Number,
      "default": 100
    },
    mana: {
      type: Number,
      "default": 50
    },
    currentMana: {
      type: Number,
      "default": 50
    },
    experience: {
      type: Number,
      "default": 0
    },
    level: {
      type: Number,
      "default": 1
    },
    tasks: {
      type: Array,
      "default": []
    },
    path: {
      type: String
    }
  });

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  app.get('/', function(req, res) {
    return res.render('index');
  });

  app.get('/login', function(req, res) {
    return res.render('login');
  });

  app.get('/:username', function(req, res) {
    console.log('requser in GET', req.params.username);
    return Character.find({
      username: req.params.username
    }, function(err, data) {
      if (err) {
        return console.log('error', err);
      } else {
        console.log('char', data);
        return res.render('dash', {
          userCharacter: data[0],
          dailies: pathTasks.dailies
        });
      }
    });
  });

  app.post('/signin', passport.authenticate('local'), function(req, res) {
    console.log(req.user.username);
    return res.redirect('/' + req.user.username);
  });

  app.get('/login', function(req, res) {
    return res.render('login');
  });

  app.post('/signup', function(req, res) {
    var newUser;
    console.log('reqBody', req.body);
    newUser = new Character({
      email: req.body.email,
      password: req.body.password,
      username: req.body.username
    });
    newUser.save();
    console.log('UserID', newUser._id);
    return res.send('success!');
  });

  app.post('/chosenpath', function(req, res) {
    console.log('user', req.user);
    return res.send('success!');
  });

  app.get('/auth/steam/', passport.authenticate('steam'), function(req, res) {
    res.redirect('/');
  });

  app.get('/auth/steam/callback', passport.authenticate('steam', {
    failureRedirect: '/login'
  }), function(req, res) {
    res.render('/', {
      steamLogin: req.query
    });
  });

  app.get('/auth/steam/return', function(req, res) {
    res.send(req.query);
  });

  app.get('/users/logout', function(req, res) {
    return req.session.destroy(function(err) {
      return res.redirect('/');
    });
  });

}).call(this);
