// Generated by CoffeeScript 1.6.3
(function() {
  var Dailies;

  Dailies = {
    exercise: ['Go to the gym', 'Go for a walk', 'Spend 20 minutes outside', 'Plan a workout schedule for the week'],
    learning: ['Read about something new for 30 minutes', 'Teach someone about something new you learned', 'Practice memory exercises'],
    eating: ['Try to limit your sugar intake today', 'Eat two pieces of fruit', 'Eat a meal without any carbs', 'Don\'t eat meals out today'],
    organize: ['Take 15 minutes to plan out your day', 'Clean out and organize one room in your house', 'Create a workspace on a desk or table'],
    finance: ['Write down what you\'re spending, and on what', 'Make a budget for today - stick to it', 'Amazon MTurks can add up!', 'Don\'t eat meals out today']
  };

  exports.Dailies = Dailies;

}).call(this);
