// Generated by CoffeeScript 1.6.3
(function() {
  var Dailies;

  Dailies = {
    exercise: ['Go to the gym', 'Go for a walk', 'Spend 20 minutes outside'],
    learning: ['Read about something new for 30 minutes', 'Teach someone about something new you learned'],
    eating: ['Try to limit your sugar intake today', 'Eat two pieces of fruit', 'Eat a meal without any carbs'],
    organize: ['Take 15 minutes to plan out your day', 'Clean out and organize one room in your house'],
    finance: ['Write down what you\'re spending, and on what', 'Make a weekly budget - stick to it']
  };

  exports.Dailies = Dailies;

}).call(this);
